pkg/controllers/core/catalogsource_controller.go

For all resources created as a result of reconciling a `CatalogSource` CR, add owner references. This includes:
- All `Package` resources
- All `BundleMetadata` resources
- Unpack `Job`s
**Motivation**
- When deleting a `CatalogSource` CR, Kubernetes garbage collection automatically cleans up child resources
- fixes #7

Add owner references in CatalogSource reconciliation logic

---

Makefile
config/crd/bases/catalogd.operatorframework.io_bundlemetadata.yaml
config/crd/bases/catalogd.operatorframework.io_catalogsources.yaml
config/crd/bases/catalogd.operatorframework.io_packages.yaml

(makefile) Polish targets

---

.github/workflows/sanity.yaml
Makefile
config/crd/bases/catalogd.operatorframework.io_catalogsources.yaml

(actions) Add sanity check

---

.goreleaser.yml
Makefile
config/default/kustomization.yaml
config/rbac/apiserver_service_account.yaml
config/rbac/kustomization.yaml
config/rbac/service_account.yaml

**Description**:
- Comment out all references and things related to the custom apiserver and etcd
- Slightly out of scope but I also updated the `make quickstart` target to use `$(KUSTOMIZE)` instead of `kubectl kustomize`
**Motivation**:
- resolves #28

Temporarily disable apiserver+etcd

---

.goreleaser.yml
Makefile
cmd/apiserver/main.go
cmd/manager/main.go
internal/version/version.go

**Description**:
- Adds an internal version package with:
- A function for getting the controller version information
- A function for getting the apiserver version information
- Updates the Makefile to set the necessary version flags when building
- Adds a `--version` flag to the controller manager
- Updates goreleaser to set the version flags when building the controller and apiserver
- In a follow up, we will have to configure the version information for the apiserver. The `apiserver-runtime` package that we are currently using to build the apiserver hardcodes version information that overrides any of the information we include. I left a TODO comment to reflect this. A solution is to update the `apiserver-runtime` tooling OR create or own implementation that we use to set the version …

add version information

---

Makefile

- Update the Makefile to export the `CERT_MGR_VERSION` environment variable when releasing
**Motivation**
- fix the problem encountered when trying to cut the v0.1.0 release: https://github.com/operator-framework/catalogd/actions/runs/4757675157/jobs/8454773378#step:7:257

(fix): export the CERT_MGR_VERSION env var for releasing

---

Makefile

- `make quickstart` used the wrong variable for version replacement in the Makefile. This PR fixes that.
**Motivation**
- The v0.1.1 release is uninstallable due to the version tag missing from the catalogd-controller deployment

fix the quickstart target's version replacement

---

pkg/controllers/core/catalogsource_controller.go

- When creating an unpack job use init containers to pull the catalog image, populate a volume with fbc configs, and use the opm image to render the configs from the volume. This ensures we are respecting the cluster pull configurations by not pulling an image within the unpack pod.
**Motivation**
- fixes #21

respect cluster image pull configurations

---

.goreleaser.yml

The quay.io/operator-framework/catalogd-controller images have not been built properly for multiple architectures and all manifests show as being for the amd64 arch.
This PR updates the `.goreleaser.yaml` file to use buildx and explicitly sets the build platform with the `--platform` flag.

update .goreleaser.yaml to properly build multi-arch images

---

Makefile

When trying to run `make build-container` I ran into an issue where the `goreleaser` target was not found. This was due to https://github.com/operator-framework/catalogd/blob/abc5a780b4cc2700bf897f8c26015b097c892636/Makefile#L81 not being updated to be `$(GORELEASER)` to work with the bingo change introduced by #75

(bugfix): in Makefile set `BUILDDEPS = $(GORELEASER)`

---

api/core/v1alpha1/bundlemetadata_types.go
config/crd/bases/catalogd.operatorframework.io_bundlemetadata.yaml
test/e2e/unpack_test.go
testdata/catalogs/test-catalog/catalog.yaml

bundlemetadata: make related images and properties optional

---

.github/workflows/release.yaml
go.mod

Bump go.mod files and GHA workflows to use go 1.20

bump to go 1.20

---

README.md

Issue: https://github.com/operator-framework/catalogd/issues/81
Update the catalogd README to reflect the current state of the project and its place in the OLM v1 project.

#81 Updated README

---

.github/workflows/release.yaml

Updates GH actions to versions which use Node 16.
Currently some of our actions produce the following warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
The above is due to usage of actions/checkout@v2.
`docker/login-action@v1` also seems to have another issue:
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Updates GH Actions to avoid using deprecated node

---

.github/workflows/unit.yaml

Equivalent of https://github.com/operator-framework/operator-controller/pull/279

Adds codecov integration

---

test/e2e/unpack_test.go

Add support to override the test catalog image using an environment variable to avoid it being hard-coded.

e2e: support env var for catalog image

---

config/manager/manager.yaml

Ideally, we would enforce restricted. However, some catalog images may not be compatible with restriced enforcement.
This is another motivation for us to treat catalog images differently from runnable images. PSA compatibility of catalog images should never be a consideration because we only need to extract static files from them. Actually running them should never be necessary.

add PSA labels to namespace for baseline enforcement

---

README.md

The operator-controller docs link was 404ing, now it links directly to a markdown file.

(docs) Fix link and misspelling

---

config/default/manager_auth_proxy_patch.yaml
go.mod
go.sum
internal/k8sutil/k8sutil.go
internal/k8sutil/k8sutil_test.go
pkg/controllers/core/catalog_controller.go
pkg/controllers/core/catalog_controller_test.go

Enable CatalogMetadataAPI via explicit flag, fix syncing issues

---

pkg/features/features.go

Closes https://github.com/operator-framework/catalogd/issues/115

Deprecate the `CatalogMetadataAPI` feature gate

---

docs/fetching-catalog-contents.md

- Adds documentation on how to fetch catalog contents via the HTTP server for both on and off cluster clients.
**Motivation**
- resolves #120

(docs): Add docs on fetching contents via HTTP server

---

api/core/v1alpha1/catalog_types.go
cmd/manager/main.go
config/crd/bases/catalogd.operatorframework.io_catalogs.yaml
config/default/manager_auth_proxy_patch.yaml
docs/fetching-catalog-contents.md
pkg/controllers/core/catalog_controller.go
pkg/controllers/core/catalog_controller_test.go
pkg/storage/localdir.go
pkg/storage/localdir_test.go
pkg/storage/storage.go
test/e2e/unpack_test.go

(server) Expose content URL on CR status

---

README.md

Resolves https://github.com/operator-framework/catalogd/issues/177

Update README with simplified make target ref

---

api/core/v1alpha1/catalog_types.go
config/crd/bases/catalogd.operatorframework.io_catalogs.yaml

Add printer columns to catalog API. Adds Phase as well as Age printer columns
Resolves https://github.com/operator-framework/catalogd/issues/172

add default printer columns

---

internal/source/image_registry_client.go
internal/source/image_registry_client_test.go

- Update the `ImageRegistry.Unpack()` implementation to attempt to remove the cache entry if `unpackImage()` fails 
- Add a new test case that ensures if the required label is missing from the image, thus failing image unpacking, an error is consistently returned
**Motivation**
- fixes #206

:bug: attempt to remove cache entry if unpack fails

---

test/e2e/e2e_suite_test.go
test/e2e/unpack_test.go

**Description**:
- Replaces the `Job` created to query the catalogd http server with a client-go `ProxyGet()` call to directly query the service. It parses the necessary information from the `status.contentURL` field of the `Catalog` resource before making the query.
**Motivation**:
- resolves #204

:seedling: replace e2e Job with client-go ProxyGet() call

---

api/core/v1alpha1/catalog_types.go
config/crd/bases/catalogd.operatorframework.io_catalogs.yaml

- Add enum validation marker for the `spec.source.type` field to fail fast at attempted creation time when an unsupported source type is specified.
**Motivation**
- Resolves #213

:bug: Add enum validation for source type

---

.goreleaser.yml

**Description**:
- Removes the cert-manager references from the installation guide on the release notes published by goreleaser. catalogd has not depended on cert-manager being installed for quite some time.
**Motivation**
- Prevent users from installing unnecessary stuff if they _only_ want to install catalogd. Also prevents the idea that catalogd has some dependency on cert-manager.

:seedling: Remove cert-manager from release note install process

---

Makefile
README.md
hack/scripts/demo-script.sh
hack/scripts/generate-asciidemo.sh

This PR was originally just bringing the in-repo animated gif demo up-to-date w.r.t. API changes, as it had lagged behind.
Based on feedback, it's rejiggered to provide the functional basis for automating the demo and hosting the resulting file at asciicast.org. 
There will need to be follow-on PRs for workflow automation and updating the readme with generated demos.

🌱  updates to enable autogenerated demo, hosted out-of-tree

---

README.md
hack/scripts/demo-script.sh
hack/scripts/generate-asciidemo.sh

:seedling: demo install from published tag

---

cmd/manager/main.go

to allow for fully writing large catalogs contents in the response

:bug: bump the catalogserver write timeout to 5 minutes

---

api/core/v1alpha1/catalog_types.go
config/crd/bases/catalogd.operatorframework.io_catalogs.yaml

:bug: add validation for pollInterval duration units

---

cmd/manager/main.go
internal/garbagecollection/garbage_collector.go
internal/garbagecollection/garbage_collector_test.go

and add it to the controller manager. Make it log errors instead of exiting. This prevents crashlooping when there are errors in the garbage collection process.

🐛 make garbage collection a runnable

---

.github/workflows/unit.yaml

:seedling: bumping codecov-action to v4

---

Makefile
go.mod
go.sum

:sparkles: bump docker deps to 25.0.5

---

.goreleaser.yml
Makefile

🌱 Makefile: fix issues with repeated evaluations

---

Makefile

This mirrors the same fix made previously in operator-controller: https://github.com/operator-framework/operator-controller/pull/790
That same fix was updated/fixed here: https://github.com/operator-framework/operator-controller/pull/804
This PR reflects the latter, fixed version.

🐛 Fix XDG_DATA_HOME build issue

---

.goreleaser.yml
Makefile
README.md
cmd/manager/main.go
config/base/default/kustomization.yaml
config/base/manager/manager.yaml
config/base/nginx-ingress/resources/nginx_ingress.yaml
config/overlays/cert-manager/kustomization.yaml
config/overlays/cert-manager/resources/certificate.yaml
docs/fetching-catalog-contents.md
hack/scripts/demo-script.sh

Wasn't really sure if we considered this a major or minor change.
This changes the default namespace for Catalogd from catalogd-system to olmv1-system as part of the effort to move all OLMv1 components to the same namespace.

⚠ Change default namespace to olmv1-system

---

.github/workflows/unit.yaml

* `functionalities` param is no longer exist. It was used to enable file fixes to ignore common lines from coverage. This feature is now seems to be on by default.
* Adding `disable_search` because we do not need for the codecov action to search for coverage files: we explicitly provide files.

🌱 Fix codecov-action params

---

test/e2e/unpack_test.go

:bug: Use url.Scheme to determine port number

---

config/base/manager/catalogserver_service.yaml
config/base/manager/manager.yaml
config/base/rbac/auth_proxy_service.yaml

As the label selector used for both catalogd and operator-controller metrics services is "control-plane: controller-manager". Hence changing the labels in both operator-controller and catalogd to make sure we do not overlap.
Refer
https://github.com/operator-framework/operator-controller/issues/955 for details

:bug: Fixing the labels for better identify metrics

---

Makefile
go.mod
go.sum
pkg/storage/localdir.go
pkg/storage/localdir_test.go

This is an inexpensive-to-implement approach which takes no action (and incurs no cost) unless:
1. the served content exceeds (a default) size of 1400 bytes; and
2. the client indicates support for compressed streaming via request header "Accept-Encoding" set to "gzip"
It's possible that we may decide later to trade CPU load for disk space, once we get an opportunity to generate some benchmarks with this approach.

🌱 adding gzip content support

---

config/base/manager/manager.yaml

✨ reduce cpu requests

---

test/tools/imageregistry/registry.sh

It looks like this is unnecessary

🌱 Remove the second installation of cert-manager

---

go.mod
go.sum
pkg/storage/localdir.go

the NYTimes original project is abandoned (last update in 2018) and there is a commonly-used well-updated fork in github.com/klauspost/compress.  It's used in traefik and other projects.  
This is a drop-in compatible library with a number of (unrelated to us) fixes.

✨ shift gzip lib to active fork

---

.goreleaser.yml
config/base/default/clustercatalogs/operatorhub.yaml

Also adds optional instructions for adding the OperatorHub.io ClusterCatalog to a cluster.
I didn't change this, but curious on thoughts regarding any changes to the README. Right now we give an example where the user copy/pastes the whole yaml file--should I change that to just reference this file instead?

✨ Include OperatorHub.io ClusterCatalog in releases

---

docs/fetching-catalog-contents.md
internal/storage/localdir.go
internal/storage/localdir_test.go

The format of catalog information from catalogd for hosted catalogs expresses as `Content-Type: application/json` but it is not delimiter-less Concatenated JSON.  Instead, due to use of the go json encoder, it is a UTF-8 JSON stream which uses newlines to delimit complete JSON objects.  This is compliant with the [jsonlines](https://jsonlines.org/) proposed MIMEtype.  
This PR adjusts the `Content-Type` field for catalogd-hosted content to `application/jsonl` to align with the desired format.  A follow-on PR will formally document the interface and convention, including this format.
Reference:
- [go.dev/src/encoding/json/stream.go](https://go.dev/src/encoding/json/stream.go) `stream.Encode` says
```golang
// Terminate each value with a newline.
// This makes the output look a little nicer …
```

✨ json-lines interface: set content-type, enforce format, document interface

---

.github/dependabot.yml

This should help group k8s dependencies into a single PR when possible.
Relevant doc: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
Similar PR in operator-controller: https://github.com/operator-framework/operator-controller/pull/1070

🌱 Add dependabot K8s dependencies group

---

.github/workflows/e2e.yaml
Makefile
test/e2e/unpack_test.go
test/e2e/util.go
test/tools/imageregistry/pre-upgrade-setup.sh
test/upgrade/unpack_test.go
test/upgrade/upgrade_suite_test.go

Testing upgrade from the latest release to the current commit.
Fixes https://github.com/operator-framework/catalogd/issues/271

✨ Add upgrade e2e tests

---

config/base/manager/manager.yaml

As this namespace is shared between catalogd operator-framework-catalogd
Fixes issue #346

:bug: Removing the catalogd from  app.kubernetes.io/name

---

api/core/v1alpha1/clustercatalog_types.go
config/base/crd/bases/olm.operatorframework.io_clustercatalogs.yaml
config/samples/core_v1alpha1_clustercatalog.yaml

Adds an int32 field to allow users to optionally set priority of catalogs. This priority value may be taken into account during bundle selection from multiple catalogs to remove ambiguity.
Fixes: https://github.com/operator-framework/operator-controller/issues/1116

✨: Catalog Priority

---

README.md
api/core/v1alpha1/clustercatalog_types.go
config/base/crd/bases/olm.operatorframework.io_clustercatalogs.yaml
docs/fetching-catalog-contents.md
internal/controllers/core/clustercatalog_controller.go
internal/controllers/core/clustercatalog_controller_test.go
test/tools/imageregistry/registry.sh

Fix #366 
_Technically_ an API breakage...

:sparkles: Remove status.phase field from the code and doc references

---

config/base/manager/webhook/patch.yaml
config/components/tls/kustomization.yaml
config/components/tls/patches/catalogd_webhook.yaml

:seedling: Move cert-manager.io patch into tls component

---

test/e2e/unpack_test.go

Just to make sure the mutating webhook adds the label.

:seedling: Add label creation checking in the e2e

---

config/base/manager/webhook/patch.yaml

Fix: #370
Should add some efficiency as it only lets the webhook fire when needed. 
If either the `olm.operatorframework.io/metadata.name` label is missing, or the label does not match the catalog name, the webhook will be allowed to fire and correct the situation.

🌱 Add matchCondition to webhook config

---

config/base/manager/webhook/patch.yaml

This makes sure we have a `name` for the resource... the only way this could happen is if `generateName` is in use. In that case, k8s will update the resource with a `name`, and we'll catch it in the webhook after that happens.

:bug: Fix matchConditions to be compatible with GenerateName

---

Makefile
config/components/tls/patches/manager_deployment_certs.yaml
config/components/tls/resources/certificate.yaml

This will cause the catalogd deployment to restart, meaning that the catalogd will update quicker (rather than waiting on k8s to update the certificates via the volume)

:seedling: Force a rename of the catalogd certificate

---

Makefile
cmd/manager/main.go
cmd/manager/main_test.go
config/base/manager/manager.yaml
config/components/tls/patches/manager_deployment_certs.yaml
internal/httputil/certutil.go
internal/httputil/main_test.go
internal/source/image_registry_client.go
internal/source/unpacker.go
test/e2e/unpack_test.go
test/tools/imageregistry/imgreg.yaml

✨ Ensure docker registry CA is trusted in e2e tests

---

internal/controllers/core/clustercatalog_controller.go
internal/source/image_registry_client.go
internal/source/image_registry_client_test.go

🐛 Fix FS cache for image refs with tags

---

internal/source/image_registry_client.go

While fixing a bug in #394 I removed optimisation for digest based image. This PR changes the unpacker so that we do not make a network call for these images: only for tag-based images.

🐛 Avoid a network call for digest based images

---

internal/source/image_registry_client.go
internal/source/image_registry_client_test.go

We should not be updating lastUnpacked status fields when we read from the cache
Fixes https://github.com/operator-framework/catalogd/issues/389

🐛 Fix unnecessary lastUnpacked status updates

---

config/base/manager/manager.yaml
go.mod
internal/controllers/core/clustercatalog_controller.go
test/upgrade/unpack_test.go

I noticed that the post-upgrade-e2e checks were actually making assertions on the ClusterCatalog before it had a change to be reconciled by the upgraded catalogd instance. This PR should fix that.

🌱 make post-upgrade-e2e checks wait for ClusterCatalog to be reconciled

---

internal/source/containers_image.go
internal/source/containers_image_test.go

🐛 unpack cache cleanup should ignore missing files

---

.github/workflows/go-verdiff.yaml

The location is different than the operator-controller repo.

:bug: Refer to the correct location for go-verdiff

---

cmd/manager/main.go
internal/controllers/core/clustercatalog_controller.go
internal/controllers/core/clustercatalog_controller_test.go

Closes [409](https://github.com/operator-framework/catalogd/issues/409)

🐛 Handle finalizers (creation and deletion) better

---

test/tools/imageregistry/pre-upgrade-setup.sh

The upgrade e2e test script was still waiting for the catalog to be unpacked

:bug: Fix wait in pre-upgrade-setup test

---

api/core/v1alpha1/clustercatalog_types.go
internal/controllers/core/clustercatalog_controller.go
internal/controllers/core/clustercatalog_controller_test.go

Closes [412](https://github.com/operator-framework/catalogd/issues/412)

⚠ Update the Progressing Status condition `Terminal` reason to `Blocked`

---

cmd/manager/main.go

✨ Use default creds if present for pulling catalog images

---

cmd/manager/main.go
internal/controllers/core/clustercatalog_controller.go
internal/controllers/core/clustercatalog_controller_test.go

🐛 main.go: improve logging for configuration of global auth

---

cmd/manager/main.go
config/base/manager/manager.yaml
go.mod
internal/controllers/core/clustercatalog_controller.go
test/upgrade/unpack_test.go

Use standard klog now that klog works with controller-runtime's expectation of a logr.Logger interface. 
We get a standard --v flag and we are more in line with k8s standards. 
We also get client-go and other low-level logging from k8s libraries at the higher verbosity levels which could be immensely helpful for debugging.

✨main.go: switch to klog-based logger

---

cmd/manager/main.go
internal/controllers/core/clustercatalog_controller.go
internal/controllers/core/clustercatalog_controller_test.go
internal/source/containers_image.go
internal/source/containers_image_test.go

For awhile in catalogd, we've had a very loose "needsUnpack" behavior where we would make the assumption that if we didn't need to unpack, then we _also_ didn't need to update the status of the object.
This means that some objects may _never_ have their status updated after an upgrade. That's problematic because upgrades may add new helpful fields or fix bugs in the way that status is reported.
This PR is a somewhat hacky fix for the situation. It solves the problem by keeping an in-memory map of the observedGeneration and resolved source, and then using _that_ as the source of truth to and then use that expected status as part of the determination of whether an unpack is required.
A new criteria of "needsUnpack" is now: "does the expected status differ from the status that is on the …

🐛clustercatalog_controller: hacky, but more correct status updating in reconciler

---

cmd/manager/main.go
internal/controllers/core/pull_secret_controller.go
internal/controllers/core/pull_secret_controller_test.go
internal/source/containers_image.go
internal/source/containers_image_test.go

RFC: https://docs.google.com/document/d/1BXD6kj5zXHcGiqvJOikU2xs8kV26TPnzEKp6n7TKD4M/edit#heading=h.x3tfh25grvnv

✨ Add PullSecret controller to save pull secret data locally

---

internal/source/containers_image.go

This fixes "pushing signatures for OCI images is not supported" error when working with signed source images.
If policy context requires signature validation for a registry we will still be performing it on pull, but we will be removing source signatures when copying into a temporary OCI layout for unpacking.

🐛 Fix pulling signed images

---

.github/workflows/release.yaml

Addresses usage of deprecated goreleaser flags

:seedling: Address goreleaser deprecated flags

---

api/core/v1alpha1/clustercatalog_types.go
cmd/manager/main.go
config/base/crd/bases/olm.operatorframework.io_clustercatalogs.yaml
internal/controllers/core/clustercatalog_controller.go
internal/controllers/core/clustercatalog_controller_test.go

:sparkles:  Adding Availability enum to catalog spec

---

internal/source/containers_image.go

When used in conjuction with a "tag-only" registries.conf mirror registry configuration, our containers/image unpacker fails. This is because we resolve a canonical ref from the tag, and then use the digest-based reference to actually copy the image, thus thwarting the tag-only configuration.
This commit ensures that we always copy the image using the reference provided in the spec.

🐛 use spec's ref instead of canonical ref when copying catalog image

---

test/upgrade/unpack_test.go

When we pushed types updates recently, we totally expected to see the e2e-upgrade test fail since it pulls in the manifests from the latest release, and they changes were breaking.  
However, we missed an erroneous update that was made to the e2e-upgrade test which presumed that the catalog data was an API access (which wasn't).

🐛 fix an erroneous e2e testdata path update

---

scripts/install.tpl.sh

We've encountered cert-manager failures in e2e, installing from release, and running the demo updates.  This introduces some additional waits on cert-manager resources to attempt to reduce these.

✨ adding additional waits to prevent e2e cert-manager failures

---

.github/workflows/tilt.yaml

🌱 tilt ci: use Go version from go.mod

---

README.md
hack/scripts/demo-script.sh

demo was not updated to work with the cert-manager changes made earlier.  
In addition, there are some new waits introduced to give some more signal around some (very) intermittent install failures from the install script. 
This script now completely eschews installation via locally-defined resources and relies entirely on the latest release's scripts/manifests to install on the local cluster, so that we have fewer scripts to maintain.

✨ updating demo to work with cert-manager, README with new demo

---

.github/workflows/demo.yaml

✨ add a demo-update generation workflow step to let us know when we have broken demo generation

---

test/upgrade/unpack_test.go

This fixes two issues made manifest in testing the upgrade-e2e case subsequent to cutting the new RC. 
1. [here](https://github.com/operator-framework/catalogd/commit/2f96c573d5a8e5197c53f8219f1e32a24d8d4b8a#diff-b104edd120983248771684630cd3f66af28359c829df801a5eea77845d459aa0R33) an accidental label change in the v1 api promotion
2. [here](https://github.com/operator-framework/catalogd/commit/2f96c573d5a8e5197c53f8219f1e32a24d8d4b8a#diff-b104edd120983248771684630cd3f66af28359c829df801a5eea77845d459aa0R69) a location which I failed to update for the new Progressing==True logic for happy path clustercatalog unpacking.  This was masked due to the fact that we knew we were making breaking changes, and the upgrade-e2e test will fail until we have cut a new release.  😞

🐛 fixes the upgrade-e2e test with v1 api

---

Makefile

We have several non-standlone Make targets
- test-e2e
- kind-load
- install
- only-deploy-manifest
The above targets rely on Kind to be running. 
Unfortunately, currently, errors returned from the Go code are pretty cryptic. Better would be an explicit catch and error when a  Kind cluster is not found when these targets are run.
Currently we have:
```bash
catalogd checking_kind_running $ make test-e2e
/Users/btofel/go/bin/ginkgo-v2.20.2  -trace -vv  test/e2e
Running Suite: E2E Suite - /Users/btofel/workspace/catalogd/test/e2e
====================================================================
Random Seed: 1729265504
Will run 1 of 1 specs
------------------------------
[BeforeSuite]
/Users/btofel/workspace/catalogd/test/e2e/e2e_suite_test.go:33
> Enter [BeforeSuite] TOP-LEVEL - …
```

🐛 Check cluster is running for non-standalone Make targets

---

hack/scripts/check-go-version.sh

* Handle new files (old version is empty)
* Handle the case where .0 patch is added/removed

:bug: Update go version checker

---

Makefile

Standardizing this method simplifies workflows and makes the project more contributor-friendly

🌱  fix: update kind-load target to ensure that works aligned with controller-operator

---

Makefile

Since docker requires a license in some scenarios, we might have contributors who prefer to use Podman. This commit introduces the changes necessary to support both.

🌱 feat: add support for Podman as a container runtime

---

Makefile

`check-cluster` is already a dependency of the `install` target, which is a dependency of `e2e`. It does not need to be a dependency of `test-e2e` which _just_ runs the tests without any setup.

:bug: Remove check-cluster dependency from test-e2e

---

.github/workflows/release.yaml

It looks like ever since we enabled the merge queue, we've been pushing a bunch of merge queue built image tags to quay.
Check out the "gh-readonly-queue-main" tags at https://quay.io/repository/operator-framework/catalogd?tab=tags&tag=latest

🌱 gha: release: only push images for main branch

---

test/e2e/metrics_endpoint_test.go

As described in the RFC https://docs.google.com/document/d/1hYOtHWcfoX_zWvy2YeolQBGuDgmP72vXMlrj9q9kPBQ/edit?tab=t.0 we would like to add the tests before get merge the PR: https://github.com/operator-framework/catalogd/pull/460 just to ensure that the metrics work at the same way before and after the changes.
Motivation: https://github.com/operator-framework/operator-controller/issues/1509

🌱 e2e: add tests to verify metrics endpoint

---

cmd/manager/main.go

Ensure HTTP/2 is disabled by default for webhooks. Disabling HTTP/2 mitigates vulnerabilities associated with:
- HTTP/2 Stream Cancellation (GHSA-qppj-fm5r-hxr3)
- HTTP/2 Rapid Reset (GHSA-4374-p667-p6c8)
While CVE fixes exist, they remain insufficient; disabling HTTP/2 helps reduce risks. For details, see: https://github.com/kubernetes/kubernetes/issues/121197

🐛 Disable HTTP/2 by Default for Webhooks to Mitigate CVE Risks

---

cmd/manager/main.go

:bug: :nit: remove log saying that http is disabled

---

README.md

Adding Availability mode to the example output and removing the PollInterval because it is an optional field and now it is called PollIntervalMinutes

:book: Updating the ClusterCatalog example

---

test/e2e/metrics_endpoint_test.go

Same PR as in operator-controller (see https://github.com/operator-framework/operator-controller/pull/1547)

🐛 test/e2e/metrics_endpoint_test.go: discover catalogd namespace and improve logging

---

go.mod
go.sum

See the release tag: https://github.com/joelanford/ignore/releases/tag/v0.1.1
Address CVE: https://github.com/advisories/GHSA-r9px-m959-cxf4.

🐛 CVE-2025-21614: Upgrade github.com/joelanford/ignore from v0.1.0 to v0.1.1 
